FILTERED_SYMBOLS = {
    '360ONE','ABCAPITAL','ADANIENSOL','ADANIENT','ADANIGREEN','ADANIPORTS','ADANIPOWER',
    'AMBUJACEM','ANGELONE','APLAPOLLO','ASHOKLEY','ASIANPAINT','ASTRAL','AUBANK','AUROPHARMA',
    'AXISBANK','BAJAJFINSV','BAJFINANCE','BANDHANBNK','BANKBARODA','BANKINDIA','BDL','BEL',
    'BHARATFORG','BHARTIARTL','BHEL','BIOCON','BLUESTARCO','BPCL','BSE','CAMS','CANBK','CDSL',
    'CGPOWER','CHOLAFIN','CIPLA','COALINDIA','COCHINSHIP','COFORGE','COLPAL','CONCOR','CROMPTON',
    'DABUR','DALBHARAT','DELHIVERY','DLF','DMART','DRREDDY','ETERNAL','FEDERALBNK','FORTIS',
    'GAIL','GLENMARK','GODFRYPHLP','GODREJCP','GODREJPROP','GRASIM','HAVELLS','HCLTECH','HDFCAMC',
    'HDFCBANK','HDFCLIFE','HINDALCO','HINDPETRO','HINDUNILVR','HINDZINC','HYUNDAI','ICICIBANK',
    'ICICIGI','ICICIPRULI','IEX','INDHOTEL','INDIANB','INDUSINDBK','INDUSTOWER','INFY','IOC',
    'IREDA','ITC','JINDALSTEL','JIOFIN','JSWENERGY','JSWSTEEL','JUBLFOOD','KALYANKJIL','KAYNES',
    'KFINTECH','KOTAKBANK','KPITTECH','LAURUSLABS','LICHSGFIN','LICI','LODHA','LT','LTF','LUPIN',
    'M&M','MANAPPURAM','MANKIND','MARICO','MAXHEALTH','MAZDOCK','MCX','MFSL','MOTHERSON',
    'MOTILALOFS','MPHASIS','MUTHOOTFIN','NAM-INDIA','NATIONALUM','NAUKRI','NESTLEIND','NTPC',
    'NYKAA','OBEROIRLTY','OIL','ONGC','PATANJALI','PAYTM','PETRONET','PFC','PGEL','PHOENIXLTD',
    'PIDILITIND','PIIND','PNB','PNBHOUSING','POLICYBZR','POWERGRID','PREMIERENE','PRESTIGE',
    'RBLBANK','RECLTD','RELIANCE','RVNL','SAIL','SBICARD','SBILIFE','SBIN','SHRIRAMFIN',
    'SONACOMS','SRF','SUNPHARMA','SUPREMEIND','SWIGGY','TATACONSUM','TATAELXSI','TATAPOWER',
    'TATASTEEL','TCS','TECHM','TIINDIA','TMPV','TRENT','UNIONBANK','UNITDSPR','UNOMINDA','UPL',
    'VBL','VEDL','VMM','VOLTAS','WAAREEENER','WIPRO','ZYDUSLIFE'
}


def filter_instruments(instruments, allowed_symbols=FILTERED_SYMBOLS):
    return [x for x in instruments if x.get('symbol') in allowed_symbols]
