const MAX_CANDLES=100;
export function trendSide(c){if(c.ema20>c.ema50&&c.ema50>c.ema50_3)return'LONG';if(c.ema20<c.ema50&&c.ema50<c.ema50_3)return'SHORT';return null}
function ema(values,p){if(!values.length)return null;const k=2/(p+1);let e=values[0];for(let i=1;i<values.length;i++)e=values[i]*k+e*(1-k);return e}
function calc(candles){const closes=candles.map(x=>Number(x.close));const e20=ema(closes,20),e50=ema(closes,50);const prior=closes.slice(0,-3);const e50_3=prior.length?ema(prior,50):e50;return{ema20:e20,ema50:e50,ema50_3:e50_3}}
const tm=c=>c.time.slice(11,16);const price=n=>Number(Number(n).toFixed(2));
export function buildCandidate(symbol,mother,children,side,time){const entry=side==='LONG'?mother.high:mother.low,sl=side==='LONG'?mother.low:mother.high;return{id:`${symbol}-${mother.time}`,symbol,side,entry:price(entry),sl:price(sl),target:price(side==='LONG'?entry+(entry-sl):entry-(sl-entry)),motherTime:mother.time,motherHigh:mother.high,motherLow:mother.low,childCount:children.length,status:'ELIGIBLE',createdAt:time,ema50:price(children.at(-1).ema50)}}
export function advanceCandidate(t,c){const time=tm(c);if(t.status==='ELIGIBLE'){if(time>'14:45')return{...t,status:'INVALIDATED',reason:'NO_ENTRY_AFTER_14:45'};if(t.side==='LONG'&&c.low<=t.motherLow)return{...t,status:'INVALIDATED',reason:'MOTHER_LOW_BROKEN'};if(t.side==='SHORT'&&c.high>=t.motherHigh)return{...t,status:'INVALIDATED',reason:'MOTHER_HIGH_BROKEN'};if(t.side==='LONG'&&c.high>t.motherHigh)return{...t,status:'ACTIVE',activatedAt:c.time};if(t.side==='SHORT'&&c.low<t.motherLow)return{...t,status:'ACTIVE',activatedAt:c.time};if(c.high<t.motherHigh&&c.low>t.motherLow){if(t.childCount>=5)return{...t,status:'INVALIDATED',reason:'MORE_THAN_5_CHILDREN'};return{...t,childCount:t.childCount+1,ema50:price(c.ema50)}}return t}if(t.status==='ACTIVE'){if(time>='15:13')return{...t,status:'HARD_EXIT',exit:price(c.close),exitTime:c.time,reason:'CAS_3:13_PM'};if(t.side==='LONG'){if(c.low<=t.sl)return{...t,status:'SL',exit:t.sl,exitTime:c.time};if(c.high>=t.target)return{...t,status:'TARGET',exit:t.target,exitTime:c.time}}else{if(c.high>=t.sl)return{...t,status:'SL',exit:t.sl,exitTime:c.time};if(c.low<=t.target)return{...t,status:'TARGET',exit:t.target,exitTime:c.time}}}return t}
function msg(type,t){const m={ELIGIBLE:`🎯 Inside @ 50 EMA\n\nStock: ${t.symbol}\nSide: ${t.side}\nEntry: ${t.entry}\nTarget: ${t.target}\nSL: ${t.sl}`,ACTIVE:`✅ TRADE ACTIVE\n\n${t.symbol} ${t.side}\nEntry: ${t.entry}\nTarget: ${t.target}\nSL: ${t.sl}`,TARGET:`🎯 TARGET HIT\n\n${t.symbol} ${t.side}\nTarget: ${t.target}`,SL:`❌ SL HIT\n\n${t.symbol} ${t.side}\nSL: ${t.sl}`,INVALIDATED:`⚠️ INVALIDATED\n\n${t.symbol} ${t.side}\nReason: ${t.reason}`,HARD_EXIT:`⏰ HARD EXIT\n\n${t.symbol} ${t.side}\nExit: ${t.exit}\nReason: CAS 3:13 PM`};return m[type]}
async function notify(type,t){if(!process.env.TELEGRAM_BOT_TOKEN||!process.env.TELEGRAM_CHAT_ID)return;const r=await fetch(`https://api.telegram.org/bot${process.env.TELEGRAM_BOT_TOKEN}/sendMessage`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({chat_id:process.env.TELEGRAM_CHAT_ID,text:msg(type,t)})});if(!r.ok)console.error('Telegram failed',await r.text())}
export async function processCandle(state,symbol,candle,{seed=false}={}){state.candles??={};state.trades??=[];const session=candle.time.slice(0,10);if(state.sessionDate&&state.sessionDate!==session)state.trades=[];state.sessionDate=session;const arr=state.candles[symbol]??[];if(arr.some(x=>x.time===candle.time))return{state,events:[]};arr.push(candle);arr.splice(0,Math.max(0,arr.length-MAX_CANDLES));const ind=calc(arr);const c={...candle,...ind};arr[arr.length-1]=c;state.candles[symbol]=arr;const events=[];
if(!seed){for(let i=0;i<state.trades.length;i++){const t=state.trades[i];if(t.symbol!==symbol||!['ELIGIBLE','ACTIVE'].includes(t.status))continue;const currentTrend=trendSide(c);if(t.status==='ACTIVE'&&c.hard_exit&&tm(c)>='15:13'){const next={...t,status:'HARD_EXIT',exit:price(c.close),exitTime:c.time,reason:'CAS_3:13_PM'};state.trades[i]=next;events.push({type:next.status,trade:next});continue}if(t.status==='ELIGIBLE'&&currentTrend&&currentTrend!==t.side){const next={...t,status:'INVALIDATED',reason:'TREND_FLIP'};state.trades[i]=next;events.push({type:next.status,trade:next});continue}const next=advanceCandidate(t,c);if(next.status!==t.status){state.trades[i]=next;events.push({type:next.status,trade:next})}}}
if(!seed&&tm(c)<='14:45'&&arr.length>=3){for(let n=1;n<=5;n++){if(arr.length<n+2)break;const m=arr.at(-(n+2)),children=arr.slice(-(n+1),-1);if(!children.every(x=>x.high<m.high&&x.low>m.low))continue;if(!children.some(x=>x.low<=x.ema50&&x.high>=x.ema50))continue;const side=trendSide(children.at(-1));if(!side)continue;const cnd=buildCandidate(symbol,m,children,side,c.time);if(!state.trades.some(t=>t.id===cnd.id)){state.trades.push(cnd);events.push({type:'ELIGIBLE',trade:cnd})}break}}
state.updatedAt=new Date().toISOString();for(const e of events)await notify(e.type,e.trade);return{state,events:events.map(e=>({type:e.type,id:e.trade.id}))}}
